pint("hello world")
q()
print("hello world")
Prestige_New <- read.csv("C:/Users/Suneth-PC/OneDrive/Desktop/BA IDU/Prestige_New.csv")
View(Prestige_New)
Summary(Prestige_New)
attach(Prestige_New)
attach(Prestige_New)
summary(Prestige_New)
occupations_data <- read.csv("Prestige_New")
str(occupations_data)
Prestige_New <- read.csv("Prestige_New.csv")
setwd("path/to/your/directory")
Prestige_New <- read.csv("Prestige_New.csv")
occupations_data <- read.csv("Prestige_New")
attach(Prestige_New)
library(Rcmdr)
attach(Prestige_New)
attach(Prestige_New)
summary(Prestige_New)
Prestige_New <- read.csv("Prestige_New.csv")
getwd()
setwd("C:\Users\Suneth-PC\OneDrive\Desktop\BA IDU")
setwd("C:/Users/Suneth-PC/OneDrive/Desktop/BA IDU")
setwd("C:/Users/Suneth-PC/OneDrive/Desktop/BA IDU")
setwd("C:/Users/Suneth-PC/OneDrive/Desktop/BA IDU")
setwd("C:/Users/Suneth-PC/OneDrive/Desktop/BA IDU")
setwd("C:/Users/Suneth-PC/OneDrive/Desktop/BA IDU")
occupations_data <- read.csv("Prestige_New.csv")
str(occupations_data)
summary(occupations_data)
min_income <- min(occupations_data$income)
max_income <- max(occupations_data$income)
mean_income <- mean(occupations_data$income)
median_income <- median(occupations_data$income
                        install.packages("DescTools")
                        install.packages("DescTools")
                        library(DescTools)
                        mode_income <- Mode(occupations_data$income)
                        cat("Minimum Income:", min_income, "\n")
                        cat("Maximum Income:", max_income, "\n")
                        cat("Mean Income:", mean_income, "\n")
                        cat("Median Income:", median_income, "\n")
                        median_income <- median(occupations_data$income)
                        cat("Median Income:", median_income, "\n")
                        cat("Mode of Income:", mode_income, "\n")
                        mode_income <- Mode(occupations_data$income)
                        cat("Minimum Income:", min_income, "\n")
                        cat("Maximum Income:", max_income, "\n")
                        cat("Mean Income:", mean_income, "\n")
                        cat("Median Income:", median_income, "\n")
                        cat("Mode of Income:", mode_income, "\n")
                        Prestige_New <- summary(Prestige_New[c("prestige", "education", "income")])
                        Prestige_New <- read.csv("Prestige_New.csv")
                        summary_stats <- summary(Prestige_New[c("prestige", "education", "income")])
                        Prestige_New <- read.csv("Prestige_New.csv")
                        summary_stats <- summary(Prestige_New[c("prestige", "education", "income")])
                        install.packages("psych")
                        library(psych)
                        Prestige_New <- read.csv("Prestige_New.csv")
                        columns_of_interest <- Prestige_New[c("prestige", "education", "income")]
                        summary_stats <- describe(columns_of_interest)
                        print(summary_stats)
                        min(Prestige_New$income)
                        min(Prestige_New$income)
                        max(Prestige_New$income)
                        mean(Prestige_New$income)
                        Median(Prestige_New$income)
                        Mode(Prestige_New$income)
                        Summary(Prestige_New$income)
                        Summary(Prestige_New$prestige)
                        Mode(Prestige_New$income)
                        mode_income <- Mode(occupations_data$income)
                        cat("Mode of Income:", mode_income, "\n")
                        median(Prestige_New$income)
                        mode(Prestige_New$income)
                        mode_income <- mode(occupations_data$income)
                        cat("Mode of Income:", mode_income, "\n")
                        summary(Prestige_New$prestige)
                        summary(Prestige_New$education)
                        summary(Prestige_New$income)
                        library(stats)
                        Prestige_New <- read.csv("Prestige_New.csv")
                        anova_result <- aov(prestige ~ occupation_type, data = Prestige_New)
                        summary(anova_result)
                        library(ggplot2)
                        Prestige_New <- read.csv("Prestige_New.csv")
                        colnames(Prestige_New)
                        anova_result <- aov(prestige ~ Occupation_Type, data = Prestige_New)
                        summary(anova_result)
                        ggplot(Prestige_New, aes(x = Occupation_Type, y = prestige)) +
                          geom_boxplot(fill = "skyblue") +
                          labs(title = "Prestige Scores Across Occupation Types",
                               x = "Occupation Type",
                               y = "Prestige Score") +
                          theme_minimal()
                        library(stats)
                        Prestige_New <- read.csv("Prestige_New.csv")
                        anova_result <- aov(prestige ~ occupation_type, data = Prestige_New)
                        anova_result <- aov(prestige ~ Occupation_Type, data = Prestige_New)
                        library(Rcmdr)
                        attach(Prestige_New)
                        Prestige_New <- read.csv("Prestige_New.csv")
                        colnames(Prestige_New)
                        anova_result <- aov(prestige ~ occupation_type, data = Prestige_New)
                        anova_result <- aov(prestige ~ occupation, data = Prestige_New)
                        anova_result <- aov(prestige ~ occupations_data, data = Prestige_New)
                        